# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build-macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:

    runs-on: macos-latest
    defaults:
          run:
            shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        environment-file: environment.yml
        activate-environment: geoutils
    - name: Install development dependencies and package
      run: |
        mamba install sphinx numpydoc sphinx_rtd_theme sphinx-autodoc-typehints sphinxcontrib-programoutput flake8 pytest matplotlib scipy pylint
        pip install -e . --no-dependencies
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -rA
